%YAML:1.0
---
rotationDegrees: 0
cannyThreshold1: 150
cannyThreshold2: 200
digitMinHeight: 5
digitMaxHeight: 100
digitYAlignment: 5
ocrMaxDist: 1000000.
trainingDataFilename: "training.yml"
binaryThreshold: 150
